### ISSUE TITLE
please release also on PyPI

### ISSUE THREAD

**Issue by GoogleCodeExporter** [qetzal/python-weather-api#31]
```
The Python Package Index is the repository of software for the Python 
programming language. When you make a new release we expect to find it there.

Please don't forget to include it when you make a new one.
```

Original issue reported on code.google.com by `hector.v...@gmail.com` on 27 Oct 2013 at 5:19

**Comment by GoogleCodeExporter** [comment]
Original comment by `jtas...@gmail.com` on 8 Feb 2014 at 4:33
- Changed state: **Accepted**
- Added labels: **Type-Task**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
Available on PyPi here: https://pypi.python.org/pypi/pywapi
```

Original comment by `jtas...@gmail.com` on 4 Jul 2014 at 4:10
- Changed state: **Fixed**

**Comment by matsaman** [comment]
This is not fixed.
